# Generated by Django 4.2.3 on 2023-07-11 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cart', models.CharField(max_length=45)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DireccionDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(default='producto_default.png', upload_to='media/images')),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('razonsocial', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=50)),
                ('rubro', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_deseada', models.PositiveIntegerField()),
                ('idcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cart')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_despacho', models.DateTimeField()),
                ('subtotal', models.PositiveIntegerField()),
                ('valordespacho', models.PositiveIntegerField()),
                ('valortotal', models.PositiveIntegerField()),
                ('metododepago', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Webpay', 'Webpay'), ('Tarjeta teloenvio', 'Tarjeta teloenvio')], max_length=50)),
                ('estadopedido', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En preparacion', 'En preparación'), ('Entregado', 'Entregado'), ('En Despacho', 'En Despacho'), ('Cancelado', 'Cancelado')], max_length=50)),
                ('carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.cart')),
                ('direccion_despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.direcciondespacho')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.pedido')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('idusuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='idcliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='principal.cliente'),
        ),
        migrations.AddField(
            model_name='cart',
            name='productos',
            field=models.ManyToManyField(through='principal.ProductoCart', to='principal.producto'),
        ),
    ]
